FORMAT: 1A
HOST: http://tolicodes.com/

# tolicodes.com
Toli's portfolio

## Clients [/clients/index.json]

### List All Clients [GET]

+ Response 200 (application/json)

        [{
          "img": "/clients/logos/amex.png",
          "url": "https://www.americanexpress.com/",
          "tag": ["Large Company", "Full Time"],
          "industry": ["Financial"],
          "tech": ["Frontend", "React", "Redux", "Node"]
        }, {
          "img": "/clients/logos/ny-fed.png",
          "url": "https://www.newyorkfed.org/",
          "tag": ["Large Company", "Full Time"],
          "industry": ["Financial", "Government"],
          "tech": ["Frontend", "Backbone", "Data Viz", "D3", "Highcharts", "Node"]
        }]